package modelo.entidad;
// Generated 08/06/2015 03:44:10 PM by Hibernate Tools 4.3.1



/**
 * Categoria generated by hbm2java
 */
public class Categoria  implements java.io.Serializable {


     private String idCategoria;
     private String nombre;

    public Categoria() {
        this.idCategoria="";
    }

	
    public Categoria(String idCategoria) {
        this.idCategoria = idCategoria;
    }
    public Categoria(String idCategoria, String nombre) {
       this.idCategoria = idCategoria;
       this.nombre = nombre;
    }
   
    public String getIdCategoria() {
        return this.idCategoria;
    }
    
    public void setIdCategoria(String idCategoria) {
        this.idCategoria = idCategoria;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


