package modelo.entidad;
// Generated 21/05/2015 04:24:37 PM by Hibernate Tools 4.3.1



/**
 * Categoria generated by hbm2java
 */
public class Categoria  implements java.io.Serializable {


     private String idCategoria;
     private String nombre;

    public Categoria() {
    }

	
    public Categoria(String idCategoria) {
        this.idCategoria = idCategoria;
    }
    public Categoria(String idCategoria, String nombre) {
       this.idCategoria = idCategoria;
       this.nombre = nombre;
    }
   
    public String getIdCategoria() {
        return this.idCategoria;
    }
    
    public void setIdCategoria(String idCategoria) {
        this.idCategoria = idCategoria;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


