package modelo.entidad;
// Generated 07/06/2015 06:59:39 PM by Hibernate Tools 4.3.1



/**
 * ControlId generated by hbm2java
 */
public class ControlId  implements java.io.Serializable {


     private String idCliente;
     private String idVenta;
     private String idPlato;

    public ControlId() {
    }

    public ControlId(String idCliente, String idVenta, String idPlato) {
       this.idCliente = idCliente;
       this.idVenta = idVenta;
       this.idPlato = idPlato;
    }
   
    public String getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(String idCliente) {
        this.idCliente = idCliente;
    }
    public String getIdVenta() {
        return this.idVenta;
    }
    
    public void setIdVenta(String idVenta) {
        this.idVenta = idVenta;
    }
    public String getIdPlato() {
        return this.idPlato;
    }
    
    public void setIdPlato(String idPlato) {
        this.idPlato = idPlato;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ControlId) ) return false;
		 ControlId castOther = ( ControlId ) other; 
         
		 return ( (this.getIdCliente()==castOther.getIdCliente()) || ( this.getIdCliente()!=null && castOther.getIdCliente()!=null && this.getIdCliente().equals(castOther.getIdCliente()) ) )
 && ( (this.getIdVenta()==castOther.getIdVenta()) || ( this.getIdVenta()!=null && castOther.getIdVenta()!=null && this.getIdVenta().equals(castOther.getIdVenta()) ) )
 && ( (this.getIdPlato()==castOther.getIdPlato()) || ( this.getIdPlato()!=null && castOther.getIdPlato()!=null && this.getIdPlato().equals(castOther.getIdPlato()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdCliente() == null ? 0 : this.getIdCliente().hashCode() );
         result = 37 * result + ( getIdVenta() == null ? 0 : this.getIdVenta().hashCode() );
         result = 37 * result + ( getIdPlato() == null ? 0 : this.getIdPlato().hashCode() );
         return result;
   }   


}


