package modelo.entidad;
// Generated 07/06/2015 06:59:39 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Ocupacion generated by hbm2java
 */
public class Ocupacion  implements java.io.Serializable {


     private String idOcupacion;
     private String nombre;
     private Set contratos = new HashSet(0);

    public Ocupacion() {
    }

	
    public Ocupacion(String idOcupacion) {
        this.idOcupacion = idOcupacion;
    }
    public Ocupacion(String idOcupacion, String nombre, Set contratos) {
       this.idOcupacion = idOcupacion;
       this.nombre = nombre;
       this.contratos = contratos;
    }
   
    public String getIdOcupacion() {
        return this.idOcupacion;
    }
    
    public void setIdOcupacion(String idOcupacion) {
        this.idOcupacion = idOcupacion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getContratos() {
        return this.contratos;
    }
    
    public void setContratos(Set contratos) {
        this.contratos = contratos;
    }




}


