package modelo.entidad;
// Generated 07/06/2015 06:59:39 PM by Hibernate Tools 4.3.1

import modelo.pojos.Cliente;
import modelo.pojos.Usuario;




/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private String idPersona;
     private String nombres;
     private String apPat;
     private String apMat;
     private String documento;
     private String genero;
     private Usuario usuario;
     private Cliente cliente;

    public Persona() {
    }

	
    public Persona(String idPersona) {
        this.idPersona = idPersona;
    }
    public Persona(String idPersona, String nombres, String apPat, String apMat, String documento, String genero, Usuario usuario, Cliente cliente) {
       this.idPersona = idPersona;
       this.nombres = nombres;
       this.apPat = apPat;
       this.apMat = apMat;
       this.documento = documento;
       this.genero = genero;
       this.usuario = usuario;
       this.cliente = cliente;
    }
   
    public String getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(String idPersona) {
        this.idPersona = idPersona;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApPat() {
        return this.apPat;
    }
    
    public void setApPat(String apPat) {
        this.apPat = apPat;
    }
    public String getApMat() {
        return this.apMat;
    }
    
    public void setApMat(String apMat) {
        this.apMat = apMat;
    }
    public String getDocumento() {
        return this.documento;
    }
    
    public void setDocumento(String documento) {
        this.documento = documento;
    }
    public String getGenero() {
        return this.genero;
    }
    
    public void setGenero(String genero) {
        this.genero = genero;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }




}


