package modelo.entidad;
// Generated 21/05/2015 04:24:37 PM by Hibernate Tools 4.3.1



/**
 * TipoCliente generated by hbm2java
 */
public class TipoCliente  implements java.io.Serializable {


     private String idTipoCliente;
     private String nombre;

    public TipoCliente() {
    }

	
    public TipoCliente(String idTipoCliente) {
        this.idTipoCliente = idTipoCliente;
    }
    public TipoCliente(String idTipoCliente, String nombre) {
       this.idTipoCliente = idTipoCliente;
       this.nombre = nombre;
    }
   
    public String getIdTipoCliente() {
        return this.idTipoCliente;
    }
    
    public void setIdTipoCliente(String idTipoCliente) {
        this.idTipoCliente = idTipoCliente;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


