package modelo.entidad;
// Generated 08/06/2015 03:44:10 PM by Hibernate Tools 4.3.1



/**
 * TipoVenta generated by hbm2java
 */
public class TipoVenta  implements java.io.Serializable {


     private String idTipoventa;
     private String nombreVenta;

    public TipoVenta() {
        this.idTipoventa="";
    }

	
    public TipoVenta(String idTipoventa) {
        this.idTipoventa = idTipoventa;
    }
    public TipoVenta(String idTipoventa, String nombreVenta) {
       this.idTipoventa = idTipoventa;
       this.nombreVenta = nombreVenta;
    }
   
    public String getIdTipoventa() {
        return this.idTipoventa;
    }
    
    public void setIdTipoventa(String idTipoventa) {
        this.idTipoventa = idTipoventa;
    }
    public String getNombreVenta() {
        return this.nombreVenta;
    }
    
    public void setNombreVenta(String nombreVenta) {
        this.nombreVenta = nombreVenta;
    }




}


