package modelo.entidad;
// Generated 07/06/2015 06:59:39 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoVenta generated by hbm2java
 */
public class TipoVenta  implements java.io.Serializable {


     private String idTipoventa;
     private String nombreVenta;
     private Set ventas = new HashSet(0);

    public TipoVenta() {
    }

	
    public TipoVenta(String idTipoventa) {
        this.idTipoventa = idTipoventa;
    }
    public TipoVenta(String idTipoventa, String nombreVenta, Set ventas) {
       this.idTipoventa = idTipoventa;
       this.nombreVenta = nombreVenta;
       this.ventas = ventas;
    }
   
    public String getIdTipoventa() {
        return this.idTipoventa;
    }
    
    public void setIdTipoventa(String idTipoventa) {
        this.idTipoventa = idTipoventa;
    }
    public String getNombreVenta() {
        return this.nombreVenta;
    }
    
    public void setNombreVenta(String nombreVenta) {
        this.nombreVenta = nombreVenta;
    }
    public Set getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set ventas) {
        this.ventas = ventas;
    }




}


