package modelo.entidad;
// Generated 26/05/2015 06:23:58 AM by Hibernate Tools 4.3.1



/**
 * TipoUsuario generated by hbm2java
 */
public class TipoUsuario  implements java.io.Serializable {


     private String idTipoUsuario;
     private String nombreUsuario;

    public TipoUsuario() {
    }

	
    public TipoUsuario(String idTipoUsuario) {
        this.idTipoUsuario = idTipoUsuario;
    }
    public TipoUsuario(String idTipoUsuario, String nombreUsuario) {
       this.idTipoUsuario = idTipoUsuario;
       this.nombreUsuario = nombreUsuario;
    }
   
    public String getIdTipoUsuario() {
        return this.idTipoUsuario;
    }
    
    public void setIdTipoUsuario(String idTipoUsuario) {
        this.idTipoUsuario = idTipoUsuario;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }




}


