package modelo.pojos;
// Generated 07/06/2015 06:59:39 PM by Hibernate Tools 4.3.1


import modelo.entidad.Persona;
import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private String idCliente;
     private Persona persona;
     private Set ventas = new HashSet(0);
     private Set contratos = new HashSet(0);
     private Set controls = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(Persona persona) {
        this.persona = persona;
    }
    public Cliente(Persona persona, Set ventas, Set contratos, Set controls) {
       this.persona = persona;
       this.ventas = ventas;
       this.contratos = contratos;
       this.controls = controls;
    }
   
    public String getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(String idCliente) {
        this.idCliente = idCliente;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public Set getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set ventas) {
        this.ventas = ventas;
    }
    public Set getContratos() {
        return this.contratos;
    }
    
    public void setContratos(Set contratos) {
        this.contratos = contratos;
    }
    public Set getControls() {
        return this.controls;
    }
    
    public void setControls(Set controls) {
        this.controls = controls;
    }




}


