package modelo.pojos;
// Generated 07/06/2015 06:59:39 PM by Hibernate Tools 4.3.1


import modelo.entidad.ControlId;
import java.util.Date;

/**
 * Control generated by hbm2java
 */
public class Control  implements java.io.Serializable {


     private ControlId id;
     private Cliente cliente;
     private DetalleVenta detalleVenta;
     private Date fecha;
     private String estado;
     private Date hora;
     private String comidadAC;

    public Control() {
    }

	
    public Control(ControlId id, Cliente cliente, DetalleVenta detalleVenta) {
        this.id = id;
        this.cliente = cliente;
        this.detalleVenta = detalleVenta;
    }
    public Control(ControlId id, Cliente cliente, DetalleVenta detalleVenta, Date fecha, String estado, Date hora, String comidadAC) {
       this.id = id;
       this.cliente = cliente;
       this.detalleVenta = detalleVenta;
       this.fecha = fecha;
       this.estado = estado;
       this.hora = hora;
       this.comidadAC = comidadAC;
    }
   
    public ControlId getId() {
        return this.id;
    }
    
    public void setId(ControlId id) {
        this.id = id;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public DetalleVenta getDetalleVenta() {
        return this.detalleVenta;
    }
    
    public void setDetalleVenta(DetalleVenta detalleVenta) {
        this.detalleVenta = detalleVenta;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Date getHora() {
        return this.hora;
    }
    
    public void setHora(Date hora) {
        this.hora = hora;
    }
    public String getComidadAC() {
        return this.comidadAC;
    }
    
    public void setComidadAC(String comidadAC) {
        this.comidadAC = comidadAC;
    }




}


