package modelo.pojos;
// Generated 07/06/2015 06:59:39 PM by Hibernate Tools 4.3.1


import modelo.entidad.Ocupacion;
import java.util.Date;

/**
 * Contrato generated by hbm2java
 */
public class Contrato  implements java.io.Serializable {


     private String idContrato;
     private Cliente cliente;
     private Ocupacion ocupacion;
     private Date fecha;
     private Date fechaIni;
     private Date fechaTerm;
     private String precio;
     private String idUsuario;

    public Contrato() {
    }

	
    public Contrato(String idContrato, Cliente cliente) {
        this.idContrato = idContrato;
        this.cliente = cliente;
    }
    public Contrato(String idContrato, Cliente cliente, Ocupacion ocupacion, Date fecha, Date fechaIni, Date fechaTerm, String precio, String idUsuario) {
       this.idContrato = idContrato;
       this.cliente = cliente;
       this.ocupacion = ocupacion;
       this.fecha = fecha;
       this.fechaIni = fechaIni;
       this.fechaTerm = fechaTerm;
       this.precio = precio;
       this.idUsuario = idUsuario;
    }
   
    public String getIdContrato() {
        return this.idContrato;
    }
    
    public void setIdContrato(String idContrato) {
        this.idContrato = idContrato;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Ocupacion getOcupacion() {
        return this.ocupacion;
    }
    
    public void setOcupacion(Ocupacion ocupacion) {
        this.ocupacion = ocupacion;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Date getFechaIni() {
        return this.fechaIni;
    }
    
    public void setFechaIni(Date fechaIni) {
        this.fechaIni = fechaIni;
    }
    public Date getFechaTerm() {
        return this.fechaTerm;
    }
    
    public void setFechaTerm(Date fechaTerm) {
        this.fechaTerm = fechaTerm;
    }
    public String getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(String precio) {
        this.precio = precio;
    }
    public String getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(String idUsuario) {
        this.idUsuario = idUsuario;
    }




}


