package modelo.pojos;
// Generated 07/06/2015 06:59:39 PM by Hibernate Tools 4.3.1



/**
 * DetalleVentaId generated by hbm2java
 */
public class DetalleVentaId  implements java.io.Serializable {


     private String idVenta;
     private String idPlato;

    public DetalleVentaId() {
    }

    public DetalleVentaId(String idVenta, String idPlato) {
       this.idVenta = idVenta;
       this.idPlato = idPlato;
    }
   
    public String getIdVenta() {
        return this.idVenta;
    }
    
    public void setIdVenta(String idVenta) {
        this.idVenta = idVenta;
    }
    public String getIdPlato() {
        return this.idPlato;
    }
    
    public void setIdPlato(String idPlato) {
        this.idPlato = idPlato;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DetalleVentaId) ) return false;
		 DetalleVentaId castOther = ( DetalleVentaId ) other; 
         
		 return ( (this.getIdVenta()==castOther.getIdVenta()) || ( this.getIdVenta()!=null && castOther.getIdVenta()!=null && this.getIdVenta().equals(castOther.getIdVenta()) ) )
 && ( (this.getIdPlato()==castOther.getIdPlato()) || ( this.getIdPlato()!=null && castOther.getIdPlato()!=null && this.getIdPlato().equals(castOther.getIdPlato()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdVenta() == null ? 0 : this.getIdVenta().hashCode() );
         result = 37 * result + ( getIdPlato() == null ? 0 : this.getIdPlato().hashCode() );
         return result;
   }   


}


