package modelo.pojos;
// Generated 07/06/2015 06:59:39 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * DetalleVenta generated by hbm2java
 */
public class DetalleVenta  implements java.io.Serializable {


     private DetalleVentaId id;
     private Plato plato;
     private Venta venta;
     private Date fecha;
     private BigDecimal precio;
     private Set controls = new HashSet(0);

    public DetalleVenta() {
    }

	
    public DetalleVenta(DetalleVentaId id, Plato plato, Venta venta) {
        this.id = id;
        this.plato = plato;
        this.venta = venta;
    }
    public DetalleVenta(DetalleVentaId id, Plato plato, Venta venta, Date fecha, BigDecimal precio, Set controls) {
       this.id = id;
       this.plato = plato;
       this.venta = venta;
       this.fecha = fecha;
       this.precio = precio;
       this.controls = controls;
    }
   
    public DetalleVentaId getId() {
        return this.id;
    }
    
    public void setId(DetalleVentaId id) {
        this.id = id;
    }
    public Plato getPlato() {
        return this.plato;
    }
    
    public void setPlato(Plato plato) {
        this.plato = plato;
    }
    public Venta getVenta() {
        return this.venta;
    }
    
    public void setVenta(Venta venta) {
        this.venta = venta;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }
    public Set getControls() {
        return this.controls;
    }
    
    public void setControls(Set controls) {
        this.controls = controls;
    }




}


