package modelo.pojos;
// Generated 07/06/2015 06:59:39 PM by Hibernate Tools 4.3.1


import modelo.entidad.Categoria;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Plato generated by hbm2java
 */
public class Plato  implements java.io.Serializable {


     private String idPlato;
     private Categoria categoria;
     private String nombre;
     private String descripcion;
     private BigDecimal stock;
     private BigDecimal precioPensionista;
     private BigDecimal precioNormal;
     private Set detalleVentas = new HashSet(0);

    public Plato() {
    }

	
    public Plato(String idPlato, Categoria categoria) {
        this.idPlato = idPlato;
        this.categoria = categoria;
    }
    public Plato(String idPlato, Categoria categoria, String nombre, String descripcion, BigDecimal stock, BigDecimal precioPensionista, BigDecimal precioNormal, Set detalleVentas) {
       this.idPlato = idPlato;
       this.categoria = categoria;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.stock = stock;
       this.precioPensionista = precioPensionista;
       this.precioNormal = precioNormal;
       this.detalleVentas = detalleVentas;
    }
   
    public String getIdPlato() {
        return this.idPlato;
    }
    
    public void setIdPlato(String idPlato) {
        this.idPlato = idPlato;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public BigDecimal getStock() {
        return this.stock;
    }
    
    public void setStock(BigDecimal stock) {
        this.stock = stock;
    }
    public BigDecimal getPrecioPensionista() {
        return this.precioPensionista;
    }
    
    public void setPrecioPensionista(BigDecimal precioPensionista) {
        this.precioPensionista = precioPensionista;
    }
    public BigDecimal getPrecioNormal() {
        return this.precioNormal;
    }
    
    public void setPrecioNormal(BigDecimal precioNormal) {
        this.precioNormal = precioNormal;
    }
    public Set getDetalleVentas() {
        return this.detalleVentas;
    }
    
    public void setDetalleVentas(Set detalleVentas) {
        this.detalleVentas = detalleVentas;
    }




}


