package modelo.pojos;
// Generated 07/06/2015 06:59:39 PM by Hibernate Tools 4.3.1


import modelo.entidad.Persona;
import modelo.entidad.TipoUsuario;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private String idUsuario;
     private Persona persona;
     private TipoUsuario tipoUsuario;
     private String login;
     private String pasword;
     private String estado;
     private Set ventas = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(Persona persona) {
        this.persona = persona;
    }
    public Usuario(Persona persona, TipoUsuario tipoUsuario, String login, String pasword, String estado, Set ventas) {
       this.persona = persona;
       this.tipoUsuario = tipoUsuario;
       this.login = login;
       this.pasword = pasword;
       this.estado = estado;
       this.ventas = ventas;
    }
   
    public String getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(String idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public TipoUsuario getTipoUsuario() {
        return this.tipoUsuario;
    }
    
    public void setTipoUsuario(TipoUsuario tipoUsuario) {
        this.tipoUsuario = tipoUsuario;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getPasword() {
        return this.pasword;
    }
    
    public void setPasword(String pasword) {
        this.pasword = pasword;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set ventas) {
        this.ventas = ventas;
    }




}


