package modelo.pojos;
// Generated 07/06/2015 06:59:39 PM by Hibernate Tools 4.3.1


import modelo.entidad.TipoVenta;
import java.util.HashSet;
import java.util.Set;

/**
 * Venta generated by hbm2java
 */
public class Venta  implements java.io.Serializable {


     private String idVenta;
     private Cliente cliente;
     private TipoVenta tipoVenta;
     private Usuario usuario;
     private String numeroVenta;
     private String comidaDac;
     private Set detalleVentas = new HashSet(0);

    public Venta() {
    }

	
    public Venta(String idVenta, Cliente cliente, Usuario usuario) {
        this.idVenta = idVenta;
        this.cliente = cliente;
        this.usuario = usuario;
    }
    public Venta(String idVenta, Cliente cliente, TipoVenta tipoVenta, Usuario usuario, String numeroVenta, String comidaDac, Set detalleVentas) {
       this.idVenta = idVenta;
       this.cliente = cliente;
       this.tipoVenta = tipoVenta;
       this.usuario = usuario;
       this.numeroVenta = numeroVenta;
       this.comidaDac = comidaDac;
       this.detalleVentas = detalleVentas;
    }
   
    public String getIdVenta() {
        return this.idVenta;
    }
    
    public void setIdVenta(String idVenta) {
        this.idVenta = idVenta;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public TipoVenta getTipoVenta() {
        return this.tipoVenta;
    }
    
    public void setTipoVenta(TipoVenta tipoVenta) {
        this.tipoVenta = tipoVenta;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getNumeroVenta() {
        return this.numeroVenta;
    }
    
    public void setNumeroVenta(String numeroVenta) {
        this.numeroVenta = numeroVenta;
    }
    public String getComidaDac() {
        return this.comidaDac;
    }
    
    public void setComidaDac(String comidaDac) {
        this.comidaDac = comidaDac;
    }
    public Set getDetalleVentas() {
        return this.detalleVentas;
    }
    
    public void setDetalleVentas(Set detalleVentas) {
        this.detalleVentas = detalleVentas;
    }




}


